FROM leosocy/robustpalmroi:v0.1.1

RUN apk add --no-cache \
        mariadb-connector-c-dev \
        python3-dev \
        build-base \
        git \
        mariadb-dev && \
    pip install -i https://mirrors.aliyun.com/pypi/simple pipenv